-- 코드를 입력하세요
WITH T1 AS (SELECT a.PRODUCT_ID, b.SALES_AMOUNT*a.PRICE AS SALES, a.PRODUCT_CODE
FROM PRODUCT AS a LEFT JOIN OFFLINE_SALE AS b
ON a.PRODUCT_ID = b.PRODUCT_ID)

SELECT PRODUCT_CODE, SUM(SALES) AS SALES
FROM T1
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE;